-- TODO if exists не завезли, нужно писать какие-то процедуры, если триггеров и последовательностей нет
-- УДАЛЕНИЕ ТРИГГЕРОВ
-- DROP TRIGGER  PARTICIPANTS_ID_BIR;
-- DROP TRIGGER SIGNERS_ID_BIR;
-- DROP TRIGGER BUFFER_XML_FILES_ID_BIR;
-- DROP TRIGGER TABULAR_PART_OF_THE_DOC_ID_BIR;
-- DROP TRIGGER DOC_HEADER_ID_BIR;
-- DROP TRIGGER PAYMENT_DOCUMENT_ID_BIR;
--
-- УДАЛЕНИЕ ПОСЛЕДОВАТЕЛЬНОСТЕЙ
-- DROP SEQUENCE XMLD_PARTICIPANTS_ID_SEQ;
-- DROP SEQUENCE XMLD_SIGNERS_ID_SEQ;
-- DROP SEQUENCE XMLD_SIGNERS_HOLDER_ID_SEQ;
-- DROP SEQUENCE XMLD_UTD_PAY_DOC_HOLDER_ID_SEQ;
-- DROP SEQUENCE XMLD_BUFFER_XML_FILES_ID_SEQ;
-- DROP SEQUENCE XMLD_UTD_PAYMENT_DOC_ID_SEQ;
--
-- УДАЛЕНИЕ ТАБЛИЦ
-- DROP TABLE XMLD_SIGNERS CASCADE CONSTRAINTS;
-- DROP TABLE XMLD_PARTICIPANTS CASCADE CONSTRAINTS;
-- DROP TABLE XMLD_UTD_HEADERS CASCADE CONSTRAINTS;
-- DROP TABLE XMLD_TABULAR_PART_OF_THE_DOC_ID_BIR CASCADE CONSTRAINTS;
-- DROP TABLE XMLD_UTD_PAYMENT_DOCUMENTS CASCADE CONSTRAINTS;
-- DROP TABLE XMLD_BUFFER_XML_FILES CASCADE CONSTRAINTS;

--ТАБЛИЦА УЧАСТНИКОВ
CREATE TABLE XMLD_PARTICIPANTS
(
    PARTICIPANT_ID               NUMBER              NOT NULL,
    CONSTRAINT PARTICIPANT_ID_PK PRIMARY KEY (PARTICIPANT_ID),
    PARTICIPANT_TYPE             VARCHAR2(100 CHAR)  NOT NULL,
    CODE_IN_CLASSIFIER           VARCHAR2(10 CHAR),
    STRUCTURAL_SUBDIVISION       VARCHAR2(1000 CHAR),
    INFO_FOR_PARTICIPANTS        VARCHAR2(255 CHAR),
    INN_OF_INDIV                 VARCHAR2(12 CHAR),
    CONSTRAINT INN_OF_INDIV_REGEXP CHECK (REGEXP_LIKE(INN_OF_INDIV, '([0-9][1-9]|[1-9][0-9])[0-9]{10}')),
    OTHER_INF_ABOUT_INDIV        VARCHAR2(255 CHAR),
    FIRST_NAME                   VARCHAR2(60 CHAR)   NOT NULL,
    SECOND_NAME                  VARCHAR2(60 CHAR)   NOT NULL,
    THIRD_NAME                   VARCHAR2(60 CHAR)   NOT NULL,
    NAME_OF_ORG                  VARCHAR2(1000 CHAR) NOT NULL,
    INN_OF_ENTREPRENEUR          VARCHAR2(12 CHAR),
    CONSTRAINT INN_OF_ENTREPRENEUR_REGEXP CHECK (REGEXP_LIKE(INN_OF_INDIV,
                                                             '([0-9][1-9]|[1-9][0-9])[0-9]{8}')),
    REASON_OF_REG                VARCHAR2(9 CHAR),
    CONSTRAINT REASON_OF_REG_REGEXP CHECK (REGEXP_LIKE(REASON_OF_REG,
                                                       '([0-9][1-9]|[1-9][0-9])([0-9]{2})([0-9A-Z]{2})([0-9]{3})')),
    IND                          VARCHAR2(6 CHAR),
    CONSTRAINT IND_REGEXP CHECK (REGEXP_LIKE(IND, '[0-9]{6}')),
    REGION_CODE                  VARCHAR2(2 CHAR),
    CONSTRAINT REGION_CODE_REGEXP CHECK (REGEXP_LIKE(REGION_CODE, '[0-9]{2}')),
    AREA                         VARCHAR2(50 CHAR),
    CITY                         VARCHAR2(50 CHAR),
    LOCALITY                     VARCHAR2(50 CHAR),
    STREET                       VARCHAR2(50 CHAR),
    HOUSE                        VARCHAR2(20 CHAR),
    HOUSING                      VARCHAR2(20 CHAR),
    FLAT                         VARCHAR2(20 CHAR),
    COUNTRY_CODE                 VARCHAR2(255 CHAR),
    ADDRESS                      VARCHAR2(255 CHAR),
    NUMBER_OF_THE_ADDRESS_OBJECT VARCHAR2(34)        NOT NULL,
    PHONE                        VARCHAR2(255 CHAR),
    EMAIL_ADDRESS                VARCHAR2(255 CHAR),
    BANK_ACC_NUMBER              VARCHAR2(20 CHAR),
    BANK_NAME                    VARCHAR2(1000 CHAR),
    BANK_IDENTIFIC_CODE          VARCHAR2(9 CHAR),
    CONSTRAINT BANK_IDENTIFIC_CODE_REGEXP CHECK (REGEXP_LIKE(BANK_IDENTIFIC_CODE, '[0-9]{9}'))
);

--ТАБЛИЦА ЗАГОЛОВКОВ ДОКУМЕНТОВ
CREATE TABLE XMLD_UTD_HEADERS
(
    UTD_ID                        NUMBER              NOT NULL,
    CONSTRAINT UTD_ID_PK PRIMARY KEY (UTD_ID),
    ID_OF_SIGNER_SELLER           NUMBER,
    CODE_OF_FORM                  VARCHAR2(7 CHAR)    NOT NULL,
    CONSTRAINT CODE_OF_FORM_CHK CHECK (CODE_OF_FORM = '1115125'),
    TYPE_OF_DOC                   VARCHAR2(6 CHAR)    NOT NULL,
    CONSTRAINT TYPE_OF_DOC_CHK CHECK (UPPER(TYPE_OF_DOC) IN ('СЧФ', 'СЧФДОП', 'ДОП')),
    NAME_OF_THE_DOC_OF_ECON       VARCHAR2(255 CHAR)  NOT NULL,
    NAME_OF_DOC_OF_ORGANIZATION   VARCHAR2(255 CHAR),
    DATE_OF_CR_OF_THE_INVOICE     DATE                NOT NULL,
    TIME_OF_CR_OF_THE_INVOICE     DATE                NOT NULL,
    NAME_OF_THE_ECON_SUB          VARCHAR2(1000 CHAR) NOT NULL,
    FOUND_OF_THE_CREATOR_FILE     VARCHAR2(120 CHAR)  NOT NULL,
    SERIAL_NUMBER_OF_THE_INVOICES VARCHAR2(1000 CHAR) NOT NULL,
    DATE_OF_INVOICING             DATE                NOT NULL,
    CODE_OF_VALUTA                CHAR(3 CHAR)        NOT NULL,
    CONSTRAINT CODE_OF_VALUTA_REGEXP CHECK (REGEXP_LIKE(CODE_OF_VALUTA, '[0-9]{3}')),
    NUMBER_OF_CORRECTION          NUMBER(3, 0)        NOT NULL,
    DATE_OF_CORRECTION            DATE                NOT NULL,
    FILE_SENDER_ID                VARCHAR2(46 CHAR)   NOT NULL,
    CONSTRAINT FILE_SENDER_ID_CHK CHECK (LENGTH(FILE_SENDER_ID) >= 4),
    FILE_RECIPIENT_ID             VARCHAR2(46 CHAR)   NOT NULL,
    CONSTRAINT FILE_RECIPIENT_ID_CHK CHECK (LENGTH(FILE_RECIPIENT_ID) >= 4),
    FILE_ID                       VARCHAR2(200 CHAR)  NOT NULL,
    GOS_CONTR_ID                  VARCHAR2(255 CHAR),
    NAME_OF_VALUTA                VARCHAR2(100 CHAR),
    CURS_OF_VALUTA                NUMBER(10, 4),
    SUM_OF_TAX                    NUMBER(19, 2)       NOT NULL,
    COST_OF_GOODS_WITHOUT_TAX     NUMBER(19, 2)       NOT NULL,
    COST_OF_GOODS_WITH_TAX        NUMBER(19, 2)       NOT NULL,
    SUM_OF_GOODS_WITHOUT_TAX      VARCHAR2(100 CHAR),
    SUM_OF_GOODS_WH_TAX           VARCHAR2(100 CHAR),
    VENDOR_PARTICIPANT_ID         NUMBER              NOT NULL,
    CONSTRAINT VENDOR_PARTICIPANT_ID_FK FOREIGN KEY (VENDOR_PARTICIPANT_ID) REFERENCES XMLD_PARTICIPANTS,
    SHIP_PARTICIPANT_ID           NUMBER              NOT NULL,
    CONSTRAINT SHIP_PARTICIPANT_ID_FK FOREIGN KEY (SHIP_PARTICIPANT_ID) REFERENCES XMLD_PARTICIPANTS,
    CONS_PARTICIPANT_ID           NUMBER              NOT NULL,
    CONSTRAINT CONS_PARTICIPANT_ID_FK FOREIGN KEY (CONS_PARTICIPANT_ID) REFERENCES XMLD_PARTICIPANTS,
    BUYER_PARTICIPANT_ID          NUMBER              NOT NULL,
    CONSTRAINT BUYER_PARTICIPANT_ID_FK FOREIGN KEY (BUYER_PARTICIPANT_ID) REFERENCES XMLD_PARTICIPANTS
);

COMMENT ON COLUMN XMLD_UTD_HEADERS.UTD_ID IS 'Идентификатор таблицы';
COMMENT ON COLUMN XMLD_UTD_HEADERS.ID_OF_SIGNER_SELLER IS 'ID на подписантов продавца';
COMMENT ON COLUMN XMLD_UTD_HEADERS.CODE_OF_FORM IS 'Код формы по Классификатору налоговой документации';
COMMENT ON COLUMN XMLD_UTD_HEADERS.TYPE_OF_DOC IS 'Тип документа';
COMMENT ON COLUMN XMLD_UTD_HEADERS.NAME_OF_THE_DOC_OF_ECON IS 'Наименование документа по факту хозяйственной жизни';
COMMENT ON COLUMN XMLD_UTD_HEADERS.NAME_OF_DOC_OF_ORGANIZATION IS 'Наименование первичного документа, определенное организацией';
COMMENT ON COLUMN XMLD_UTD_HEADERS.DATE_OF_CR_OF_THE_INVOICE IS 'Дата формирования файла обмена счета-фактуры';
COMMENT ON COLUMN XMLD_UTD_HEADERS.TIME_OF_CR_OF_THE_INVOICE IS 'Время формирования файла обмена счета-фактуры';
COMMENT ON COLUMN XMLD_UTD_HEADERS.NAME_OF_THE_ECON_SUB IS 'Наименование экономического субъекта - составителя файла обмена счета-фактуры';
COMMENT ON COLUMN XMLD_UTD_HEADERS.FOUND_OF_THE_CREATOR_FILE IS 'Основание, по которому экономический субъект является составителем';
COMMENT ON COLUMN XMLD_UTD_HEADERS.SERIAL_NUMBER_OF_THE_INVOICES IS 'Порядковый номер счета-фактуры';
COMMENT ON COLUMN XMLD_UTD_HEADERS.DATE_OF_INVOICING IS 'Дата составления счета-фактуры';
COMMENT ON COLUMN XMLD_UTD_HEADERS.CODE_OF_VALUTA IS 'Код  валюты согласно ОКВ';
COMMENT ON COLUMN XMLD_UTD_HEADERS.NUMBER_OF_CORRECTION IS 'Номер исправления';
COMMENT ON COLUMN XMLD_UTD_HEADERS.DATE_OF_CORRECTION IS 'Дата исправления';
COMMENT ON COLUMN XMLD_UTD_HEADERS.FILE_SENDER_ID IS 'Идентификатор – отправителя файла обмена счета-фактуры';
COMMENT ON COLUMN XMLD_UTD_HEADERS.FILE_RECIPIENT_ID IS 'Идентификатор – получателя файла обмена счета-фактуры';
COMMENT ON COLUMN XMLD_UTD_HEADERS.FILE_ID IS 'Идентификатор файла';
COMMENT ON COLUMN XMLD_UTD_HEADERS.GOS_CONTR_ID IS 'Идентификатор государственного контракта';
COMMENT ON COLUMN XMLD_UTD_HEADERS.NAME_OF_VALUTA IS 'Наименование валюты согласно (ОКВ)';
COMMENT ON COLUMN XMLD_UTD_HEADERS.CURS_OF_VALUTA IS 'Курс валюты';
COMMENT ON COLUMN XMLD_UTD_HEADERS.SUM_OF_TAX IS 'Стоимость товаров, без налога - всего ';
COMMENT ON COLUMN XMLD_UTD_HEADERS.COST_OF_GOODS_WITHOUT_TAX IS 'Стоимость товаров,с налогом - всего ';
COMMENT ON COLUMN XMLD_UTD_HEADERS.COST_OF_GOODS_WITH_TAX IS 'Сумма налога, предъявляемая покупателю';
COMMENT ON COLUMN XMLD_UTD_HEADERS.SUM_OF_GOODS_WITHOUT_TAX IS 'Суммма без НДС';
COMMENT ON COLUMN XMLD_UTD_HEADERS.SUM_OF_GOODS_WH_TAX IS 'Суммма НДС';
COMMENT ON COLUMN XMLD_UTD_HEADERS.VENDOR_PARTICIPANT_ID IS 'Идентификатор продавца';
COMMENT ON COLUMN XMLD_UTD_HEADERS.SHIP_PARTICIPANT_ID IS 'Идентификатор грузоотправителя';
COMMENT ON COLUMN XMLD_UTD_HEADERS.CONS_PARTICIPANT_ID IS 'Идентификатор грузополучателя';
COMMENT ON COLUMN XMLD_UTD_HEADERS.BUYER_PARTICIPANT_ID IS 'Идентификатор покупателя';

--ТАБЛИЧНАЯ ЧАСТЬ
CREATE TABLE XMLD_UTD_LINES
(
    UTD_ID                        NUMBER NOT NULL,
    CONSTRAINT UTD_ID_FK FOREIGN KEY (UTD_ID) REFERENCES XMLD_UTD_HEADERS,
    UTD_LINE_ID                   NUMBER NOT NULL,
    CONSTRAINT UTD_LINE_ID_PK PRIMARY KEY (UTD_LINE_ID),
    HOLDER_ID                     NUMBER NOT NULL,
    NUMBER_OF_ROW                 NUMBER(6),
    NAME_OF_PRODUCT               VARCHAR2(1000 CHAR),
    UNIT_CODE                     VARCHAR2(4 CHAR),
    QUANTITY                      NUMBER(26, 11),
    PRICE_OF_UNIT                 NUMBER(26, 11),
    SUM_OF_PRODUCT_WITHOUT_TAX    NUMBER(19, 2),
    TAX_RATE                      VARCHAR2(7 CHAR),
    CONSTRAINT TAX_RATE_CK CHECK (TAX_RATE IN ('0%', '10%', '18%', '10/110', '18/118', 'без НДС')),
    SUM_OF_PRODUCT_WITH_TAX       NUMBER(19, 2),
    SUM_OF_EXCISE                 VARCHAR2(100 CHAR),
    OF_WITHOUT_EXCISE             VARCHAR2(100 CHAR),
    SUM_OF_TAX                    NUMBER(19, 2),
    GOODS_WITHOUT_TAX             VARCHAR2(100 CHAR),
    COUNTRY_CODE_OF_PRODUCT       VARCHAR2(3 CHAR),
    CONSTRAINT COUNTRY_CODE_OF_PRODUCT_CH CHECK (LENGTH(COUNTRY_CODE_OF_PRODUCT) = 3),
    NUMBER_T_D                    VARCHAR2(29 CHAR),
    ID                            VARCHAR2(50 CHAR),
    VALUE                         VARCHAR2(2000 CHAR),
    ATTRIBUTE_OF_PRODUCT          VARCHAR2(1 CHAR),
    CONSTRAINT ATTRIBUTE_OF_PRODUCT_CK CHECK (ATTRIBUTE_OF_PRODUCT IN ('1', '2', '3', '4', '5')),
    OTHER_INFO_ABOUT_PRODUCT      VARCHAR2(4 CHAR),
    CODE_OF_PRODUCT               VARCHAR2(255 CHAR),
    UNIT_NAME                     VARCHAR2(255 CHAR),
    BRIEF_NAME_OF_COUNTRY_OF_PROD VARCHAR2(255 CHAR),
    QUANTITY_OF_LETTING_GO        NUMBER(15, 11),
    COR_ACC_DEBIT                 VARCHAR2(9 CHAR),
    CONSTRAINT COR_ACC_DEBIT_CK CHECK (LENGTH(COR_ACC_DEBIT) = 9),
    COR_ACC_CREDIT                VARCHAR2(9 CHAR),
    CONSTRAINT COR_ACC_CREDIT_CK CHECK (LENGTH(COR_ACC_CREDIT) = 9)
);

COMMENT ON COLUMN XMLD_UTD_LINES.UTD_LINE_ID IS 'Идентификатор строки';
COMMENT ON COLUMN XMLD_UTD_LINES.HOLDER_ID IS 'Ссылка на источник';
COMMENT ON COLUMN XMLD_UTD_LINES.NUMBER_OF_ROW IS 'Номер строки таблицы';
COMMENT ON COLUMN XMLD_UTD_LINES.NAME_OF_PRODUCT IS 'Наименование товара';
COMMENT ON COLUMN XMLD_UTD_LINES.UNIT_CODE IS 'ОКЕИ_Товара';
COMMENT ON COLUMN XMLD_UTD_LINES.QUANTITY IS 'Количество товара';
COMMENT ON COLUMN XMLD_UTD_LINES.PRICE_OF_UNIT IS 'Цена товара';
COMMENT ON COLUMN XMLD_UTD_LINES.SUM_OF_PRODUCT_WITHOUT_TAX IS 'Стоимость товаров, без налога - всего';
COMMENT ON COLUMN XMLD_UTD_LINES.TAX_RATE IS 'Налоговая ставка';
COMMENT ON COLUMN XMLD_UTD_LINES.SUM_OF_PRODUCT_WITH_TAX IS 'Стоимость товаров, с налогом - всего';
COMMENT ON COLUMN XMLD_UTD_LINES.SUM_OF_EXCISE IS 'Сумма акциза';
COMMENT ON COLUMN XMLD_UTD_LINES.OF_WITHOUT_EXCISE IS 'Без акциза';
COMMENT ON COLUMN XMLD_UTD_LINES.SUM_OF_TAX IS 'Сумма налога, предъявляемая покупателю';
COMMENT ON COLUMN XMLD_UTD_LINES.GOODS_WITHOUT_TAX IS 'Суммма без НДС';
COMMENT ON COLUMN XMLD_UTD_LINES.COUNTRY_CODE_OF_PRODUCT IS 'Цифровой код страны происхождения товара';
COMMENT ON COLUMN XMLD_UTD_LINES.NUMBER_T_D IS 'Номер таможенной декларации';
COMMENT ON COLUMN XMLD_UTD_LINES.ID IS 'Идентефикатор';
COMMENT ON COLUMN XMLD_UTD_LINES.VALUE IS ' Значение';
COMMENT ON COLUMN XMLD_UTD_LINES.ATTRIBUTE_OF_PRODUCT IS 'Признак';
COMMENT ON COLUMN XMLD_UTD_LINES.OTHER_INFO_ABOUT_PRODUCT IS 'Дополнительная информация о признаке';
COMMENT ON COLUMN XMLD_UTD_LINES.CODE_OF_PRODUCT IS 'Характеристика/код/артикул/сорт товара';
COMMENT ON COLUMN XMLD_UTD_LINES.UNIT_NAME IS 'Наименование единицы измерения';
COMMENT ON COLUMN XMLD_UTD_LINES.BRIEF_NAME_OF_COUNTRY_OF_PROD IS 'Краткое наименование страны происхождения товара';
COMMENT ON COLUMN XMLD_UTD_LINES.QUANTITY_OF_LETTING_GO IS 'Количество надлежит отпустить';
COMMENT ON COLUMN XMLD_UTD_LINES.COR_ACC_DEBIT IS 'Корреспондирующие счета: дебет';
COMMENT ON COLUMN XMLD_UTD_LINES.COR_ACC_CREDIT IS 'Корреспондирующие счета: кредит';


COMMENT ON COLUMN XMLD_PARTICIPANTS.PARTICIPANT_ID IS 'Идентификатор участника';
COMMENT ON COLUMN XMLD_PARTICIPANTS.PARTICIPANT_TYPE IS 'Тип участника';
COMMENT ON COLUMN XMLD_PARTICIPANTS.INN_OF_INDIV IS 'Тип участника';
COMMENT ON COLUMN XMLD_PARTICIPANTS.CODE_IN_CLASSIFIER IS 'Код в общероссийском классификаторе предприятий и организаций';
COMMENT ON COLUMN XMLD_PARTICIPANTS.STRUCTURAL_SUBDIVISION IS 'Структурное подразделение';
COMMENT ON COLUMN XMLD_PARTICIPANTS.INFO_FOR_PARTICIPANTS IS 'Информация для участника документооборота';
COMMENT ON COLUMN XMLD_PARTICIPANTS.INN_OF_INDIV IS 'ИНН физического лица';
COMMENT ON COLUMN XMLD_PARTICIPANTS.OTHER_INF_ABOUT_INDIV IS 'Другие сведения о физическом лице';
COMMENT ON COLUMN XMLD_PARTICIPANTS.SECOND_NAME IS 'Фамилия';
COMMENT ON COLUMN XMLD_PARTICIPANTS.FIRST_NAME IS 'Имя';
COMMENT ON COLUMN XMLD_PARTICIPANTS.NAME_OF_ORG IS 'Название организации';
COMMENT ON COLUMN XMLD_PARTICIPANTS.INN_OF_ENTREPRENEUR IS 'ИНН юридического лица';
COMMENT ON COLUMN XMLD_PARTICIPANTS.REASON_OF_REG IS 'Код причины постановки на учет';
COMMENT ON COLUMN XMLD_PARTICIPANTS.IND IS 'Индекс';
COMMENT ON COLUMN XMLD_PARTICIPANTS.REGION_CODE IS 'Код региона';
COMMENT ON COLUMN XMLD_PARTICIPANTS.AREA IS 'Район';
COMMENT ON COLUMN XMLD_PARTICIPANTS.CITY IS 'Город';
COMMENT ON COLUMN XMLD_PARTICIPANTS.LOCALITY IS 'Населенный пункт';
COMMENT ON COLUMN XMLD_PARTICIPANTS.STREET IS 'Улица';
COMMENT ON COLUMN XMLD_PARTICIPANTS.HOUSE IS 'Дом';
COMMENT ON COLUMN XMLD_PARTICIPANTS.HOUSING IS 'Корпус';
COMMENT ON COLUMN XMLD_PARTICIPANTS.FLAT IS 'Квартира';
COMMENT ON COLUMN XMLD_PARTICIPANTS.COUNTRY_CODE IS 'Код страны';
COMMENT ON COLUMN XMLD_PARTICIPANTS.ADDRESS IS 'Адрес';
COMMENT ON COLUMN XMLD_PARTICIPANTS.NUMBER_OF_THE_ADDRESS_OBJECT IS 'Уникальный номер адреса объекта адресации в государственном адресном реестре';
COMMENT ON COLUMN XMLD_PARTICIPANTS.PHONE IS 'Телефон';
COMMENT ON COLUMN XMLD_PARTICIPANTS.EMAIL_ADDRESS IS 'Электронная почта';
COMMENT ON COLUMN XMLD_PARTICIPANTS.BANK_ACC_NUMBER IS 'Номер банковского счета';
COMMENT ON COLUMN XMLD_PARTICIPANTS.BANK_NAME IS 'Название банка';
COMMENT ON COLUMN XMLD_PARTICIPANTS.BANK_IDENTIFIC_CODE IS 'Банковский идентификационный код';

--ТАБЛИЦА ПОДПИСАНТОВ
CREATE TABLE XMLD_SIGNERS
(
    SIGNER_ID             NUMBER              NOT NULL,
    CONSTRAINT XMLD_SIGNERS_PK PRIMARY KEY (SIGNER_ID),
    HOLDER_ID             NUMBER              NOT NULL,
    SIGNER_AUT            NUMBER              NOT NULL CHECK (SIGNER_AUT IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 10)),
    SIGNER_STAT           VARCHAR2(1 CHAR)    NOT NULL,
    CONSTRAINT SIGNER_STAT_NOT_NULL CHECK ((SIGNER_STAT = '3' AND ORG_AUT_BAS IS NOT NULL) OR SIGNER_STAT != '3'),
    CONSTRAINT SIGNER_STAT_VALID CHECK (SIGNER_STAT IN (1, 2, 3, 4)),
    SIGNER_AUT_BAS        VARCHAR2(255 CHAR)  NOT NULL,
    ORG_AUT_BAS           VARCHAR2(255 CHAR),
    SIGNER_TYPE           VARCHAR2(2 CHAR)    NOT NULL,
    CONSTRAINT SIGNER_TYPE_CHK CHECK (UPPER(SIGNER_TYPE) in ('ФЛ', 'ЮЛ', 'ИП')),
    REQ_OF_THE_CERTIF     VARCHAR2(100 CHAR),
    INN_OF_INDIV          VARCHAR2(12 CHAR),
    OTHER_INF_ABOUT_INDIV VARCHAR2(255 CHAR),
    INDIV_NOT_NULL_INN    VARCHAR2(100 CHAR),
    INN_OF_ENTREPRENEUR   VARCHAR2(10)        NOT NULL,
    NAME_OF_ORG           VARCHAR2(1000 CHAR) NOT NULL,
    POS                   VARCHAR2(128 CHAR)  NOT NULL,
    FIRST_NAME            VARCHAR2(60 CHAR)   NOT NULL,
    SECOND_NAME           VARCHAR2(60 CHAR)   NOT NULL,
    THIRD_NAME            VARCHAR2(60 CHAR)   NOT NULL,
    CREATE_DATE           DATE                NOT NULL,
    UPDATE_DATE           DATE                NOT NULL
);
COMMENT ON COLUMN XMLD_SIGNERS.SIGNER_ID IS 'Идентификатор подписанта';
COMMENT ON COLUMN XMLD_SIGNERS.HOLDER_ID IS 'Ссылка на источник';
COMMENT ON COLUMN XMLD_SIGNERS.SIGNER_AUT IS 'Область полномочий подписанта';
COMMENT ON COLUMN XMLD_SIGNERS.SIGNER_STAT IS 'Статус подписанта';
COMMENT ON COLUMN XMLD_SIGNERS.SIGNER_AUT_BAS IS 'Основание полномочий (доверия)';
COMMENT ON COLUMN XMLD_SIGNERS.ORG_AUT_BAS IS 'Основание полномочий (доверия) организации';
COMMENT ON COLUMN XMLD_SIGNERS.SIGNER_TYPE IS 'Тип подписанта';
COMMENT ON COLUMN XMLD_SIGNERS.REQ_OF_THE_CERTIF IS 'Реквизиты свидетельства о государственной регистрации';
COMMENT ON COLUMN XMLD_SIGNERS.INN_OF_INDIV IS 'ИНН физического лица';
COMMENT ON COLUMN XMLD_SIGNERS.OTHER_INF_ABOUT_INDIV IS 'Другие сведения о физическом лице';
COMMENT ON COLUMN XMLD_SIGNERS.INDIV_NOT_NULL_INN IS 'Реквизиты свидетельства о государственной регистрации (случай ИП)';
COMMENT ON COLUMN XMLD_SIGNERS.INN_OF_ENTREPRENEUR IS 'ИНН юридического лица';
COMMENT ON COLUMN XMLD_SIGNERS.NAME_OF_ORG IS 'Название организации';
COMMENT ON COLUMN XMLD_SIGNERS.POS IS 'Должность';
COMMENT ON COLUMN XMLD_SIGNERS.SECOND_NAME IS 'Фамилия';
COMMENT ON COLUMN XMLD_SIGNERS.FIRST_NAME IS 'Имя';
COMMENT ON COLUMN XMLD_SIGNERS.THIRD_NAME IS 'Отчество';
COMMENT ON COLUMN XMLD_SIGNERS.CREATE_DATE IS 'Дата создания';
COMMENT ON COLUMN XMLD_SIGNERS.UPDATE_DATE IS 'Дата обновления';

--BUFFER
CREATE TABLE XMLD_BUFFER_XML_FILES
(
    XML_ID       NUMBER NOT NULL,
    CONSTRAINT XML_ID_PK PRIMARY KEY (XML_ID),
    XML_CONTENT  CLOB,
    XML_RESOURCE VARCHAR2(20 CHAR),
    CONSTRAINT XML_RESOURCE_CK CHECK (XML_RESOURCE IN ('WEB-SERVICE', 'MANUAL', 'FILESYSTEM')),
    RECORD_DATE  DATE
);

COMMENT ON COLUMN XMLD_BUFFER_XML_FILES.XML_ID IS 'Идентификатор записи табицы';
COMMENT ON COLUMN XMLD_BUFFER_XML_FILES.XML_CONTENT IS 'Содержимое XML-файла';
COMMENT ON COLUMN XMLD_BUFFER_XML_FILES.XML_RESOURCE IS 'В ручную, из файла, по сети';
COMMENT ON COLUMN XMLD_BUFFER_XML_FILES.RECORD_DATE IS 'Дата записи';

CREATE SEQUENCE XMLD_PARTICIPANTS_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 50;

CREATE SEQUENCE XMLD_SIGNERS_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 50;

CREATE SEQUENCE XMLD_SIGNERS_HOLDER_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 50;

CREATE SEQUENCE XMLD_UTD_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 50;

CREATE SEQUENCE XMLD_UTD_LINES_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 50;

CREATE SEQUENCE XMLD_UTD_PAYMENT_DOC_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 50;

CREATE SEQUENCE XMLD_BUFFER_XML_FILES_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 50;

CREATE TRIGGER PARTICIPANTS_ID_BIR
    BEFORE INSERT
    ON XMLD_PARTICIPANTS
    FOR EACH ROW
BEGIN
    :NEW.PARTICIPANT_ID := XMLD_PARTICIPANTS_ID_SEQ.NEXTVAL;
END;

CREATE TRIGGER SIGNERS_ID_BIR
    BEFORE INSERT
    ON XMLD_SIGNERS
    FOR EACH ROW
BEGIN
    :NEW.SIGNER_ID := XMLD_SIGNERS_ID_SEQ.NEXTVAL;
END;


CREATE TRIGGER UTD_ID_BIR
    BEFORE INSERT
    ON XMLD_UTD_HEADERS
    FOR EACH ROW
BEGIN
    :NEW.UTD_ID := XMLD_UTD_ID_SEQ.NEXTVAL;
END;


CREATE TRIGGER UTD_LINES_ID_BIR
    BEFORE INSERT
    ON XMLD_UTD_LINES
    FOR EACH ROW
BEGIN
    :NEW.UTD_ID := XMLD_UTD_LINES_ID_SEQ.NEXTVAL;
END;
